-- Thêm dữ liệu dịch vụ
INSERT INTO services (title, company_id, description, features, icon, category, price_range, is_featured) VALUES
('Giải Pháp AI & Machine Learning', 1, 'Phát triển các hệ thống AI tiên tiến, từ xử lý ngôn ngữ tự nhiên đến computer vision và deep learning.', ARRAY['Natural Language Processing', 'Computer Vision', 'Predictive Analytics', 'Chatbot Development'], 'brain', 'AI', 'Từ 50,000 USD', true),
('Bảo Mật & Giám Sát Thông Minh', 2, 'Hệ thống bảo mật toàn diện với AI, IoT security và real-time monitoring cho doanh nghiệp.', ARRAY['IoT Security', 'Real-time Monitoring', 'Threat Detection', 'Access Control'], 'shield', 'Security', 'Từ 30,000 USD', true),
('E-commerce & Emotion Analytics', 3, 'Nền tảng thương mại điện tử tích hợp AI phân tích cảm xúc để tối ưu trải nghiệm khách hàng.', ARRAY['Emotion Recognition', 'Customer Analytics', 'Personalization', 'Conversion Optimization'], 'heart', 'E-commerce', 'Từ 25,000 USD', true),
('Phân Tích Dữ Liệu & Business Intelligence', 4, 'Công cụ phân tích hành vi người dùng và tối ưu hóa quy trình kinh doanh.', ARRAY['Data Visualization', 'Behavioral Analytics', 'Performance Tracking', 'Predictive Insights'], 'clock', 'Analytics', 'Từ 20,000 USD', true),
('Enterprise OS & Automation', 5, 'Hệ điều hành doanh nghiệp thông minh với khả năng tự động hóa và tối ưu quy trình.', ARRAY['Process Automation', 'System Integration', 'Workflow Optimization', 'Enterprise Management'], 'cpu', 'Enterprise', 'Từ 100,000 USD', true),
('Custom Software Development', 6, 'Phát triển phần mềm tùy chỉnh theo yêu cầu riêng của doanh nghiệp', ARRAY['Custom Development', 'Agile Methodology', 'Quality Assurance', 'Maintenance'], 'code', 'Development', 'Từ 15,000 USD', false),
('Data Management & Analytics', 6, 'Quản lý và phân tích dữ liệu lớn với các công cụ hiện đại', ARRAY['Big Data', 'Data Warehousing', 'Business Intelligence', 'Data Mining'], 'database', 'Data', 'Từ 18,000 USD', false),
('Cloud Solutions & Migration', 6, 'Giải pháp đám mây và di chuyển hệ thống lên cloud', ARRAY['Cloud Migration', 'AWS/Azure/GCP', 'Serverless Architecture', 'Cloud Security'], 'cloud', 'Cloud', 'Từ 20,000 USD', false),
('Mobile App Development', 6, 'Phát triển ứng dụng di động cho iOS và Android', ARRAY['Native Apps', 'Cross-platform', 'UI/UX Design', 'App Store Optimization'], 'smartphone', 'Mobile', 'Từ 12,000 USD', false),
('Web Development & Design', 6, 'Thiết kế và phát triển website chuyên nghiệp', ARRAY['Responsive Design', 'Frontend/Backend', 'CMS Integration', 'Performance Optimization'], 'monitor', 'Web', 'Từ 8,000 USD', false),
('Technical Support & Maintenance', 6, 'Hỗ trợ kỹ thuật và bảo trì hệ thống 24/7', ARRAY['24/7 Support', 'Preventive Maintenance', 'Issue Resolution', 'System Updates'], 'headphones', 'Support', 'Từ 5,000 USD/năm', false);